# Conversion to YAML from Properties format
# Warnings:
# - The yaml file had comments which are lost in the refactoring!
spring:
  application:
    name: MS-Plazoleta

  datasource:
    url: jdbc:mysql://localhost:3306/ms_plazoleta
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
  management:
    endpoints:
      web:
        exposure:
          include: "*"
  cloud:
    config:
      enabled: false
    import-check:
      enabled: false